on: [push]

jobs:
  tests:
    name: transform tokens
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Adzz/jest_test_action@v1.0.0
        with:
          command: transform-tokens
