on:
  push:
    branches: [ main ]
jobs:
  transformTokens:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: "16.x"

    - name: Install dependencies
      run: npm install

    - name: Run Transformer
      run: npm transform-tokens
